# Generated by Django 4.2 on 2023-12-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ManyToManyField(related_name='semester_subject', to='subject.subject')),
                ('teacher', models.ManyToManyField(related_name='teacher_subject', to='teacher.teacherprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
