# Generated by Django 5.0 on 2023-12-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_identity',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_student', True), ('is_teacher', False)), models.Q(('is_student', False), ('is_teacher', True)), _connector='OR'), name='unique_identity'),
        ),
    ]
